shop_site/shop/urls.py
from django.urls import path
from shop.views import (
    HomePage, ProductsPage, ArticleDetail
)


app_name = 'shop'

urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('categories/<category>/', ProductsPage.as_view(), name='products'),
    path('categories/<category>/<sub_cat_1>/', ProductsPage.as_view(), name='products'),
    path('categories/<category>/<sub_cat_1>/<sub_cat_2>/', ProductsPage.as_view(), name='products'),
    path('article/<slug:slug>/', ArticleDetail.as_view(), name='about_article'),
]

shop_site/shop_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('templates/', include('shop.urls')),
    path('api/', include('shop_api.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_site/shop/models.py
from django.core.exceptions import ValidationError

from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify



# Create your models here.
class Item(models.Model):
    article = models.ForeignKey('Article', on_delete=models.CASCADE, related_name='items')
    price = models.FloatField(default=0)
    size = models.CharField(max_length=100, blank=True, null=True)
    mass = models.CharField(max_length=100, blank=True, null=True)
    volume = models.CharField(max_length=100, blank=True, null=True)

    sale = models.BooleanField(default=False)
    sale_rate = models.FloatField(default=0)
    sale_price = models.FloatField(blank=True)

    amount_avaliable = models.PositiveIntegerField(default=0)
    in_stock = models.BooleanField(default=False, editable=False)

    def apply_sale(self, rate):
        if rate > 1 or rate < 0:
            raise ValueError(
                _('invalid rate value (should be in span from 0 to 1)'),
                params={'rate': rate},
            )
        self.sale = True
        self.sale_rate = rate
        self.sale_price = round(self.price * (1-rate), 2)
        self.save()

    def unapply_sale(self):
        self.sale = False
        self.sale_rate = 0
        self.save()

    def save(self, *args, **kwargs):
        if self.sale == False:
            self.sale_price = self.price

        if self.amount_avaliable == 0:
            self.in_stock = False
        else:
            self.in_stock = True
        print(self.price)

        super().save(*args, **kwargs)

    def add_items(self, amount):
        if not isinstance(amount, int) or amount < 0:
            raise ValueError(
                _('invalid amount'),
                params={'amount': amount},
            )
        self.amount_avaliable += amount
        self.save()

    def rem_items(self, amount):
        if not isinstance(amount, int) or amount < 0:
            raise ValueError(
                _('invalid amount'),
                params={'amount': amount},
            )
        self.amount_avaliable -= amount
        if self.amount_avaliable < 0:
            self.amount_avaliable = 0
        self.save()

    def __str__(self):
        if self.size:
            return str(self.article) + ', ' + str(self.size)
        if self.mass:
            return str(self.article) + ', ' + str(self.mass)
        if self.volume:
            return str(self.article) + ', ' + str(self.volume)
        return str(self.article)

    class Meta:
        ordering = ['article']


class Article(models.Model):
    image = models.ImageField(upload_to='shop/articles/', blank=True, null=True)
    title = models.CharField(max_length=100)
    brand = models.ForeignKey('Brand', on_delete=models.CASCADE, related_name='articles')
    description = models.TextField(blank=True)
    contents = models.TextField(blank=True)
    manual = models.TextField(blank=True)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, related_name='articles')

    reviews = models.ManyToManyField('Review', blank=True)
    average_rate = models.FloatField(default=0)

    slug = models.SlugField(allow_unicode=True, null=True, unique=True, editable=False)

    def save(self, *args, **kwargs):
        plain_text_cyrilic = ' '.join([str(self.brand), str(self.title)])
        plain_text_latin = transliterate(plain_text_cyrilic)
        self.slug = slugify(plain_text_latin)
        if self.id:
            self.average_rate = self.get_average_rate()
        super().save(*args, **kwargs)

    def get_average_rate(self):
        total_rate = 0
        for rev in self.reviews.all():
            total_rate += rev.rate
        num_of_voters = 1
        if self.reviews.count() != 0:
            num_of_voters = self.reviews.count()

        avreage_rate = total_rate / num_of_voters

        return round(avreage_rate,  1)

    def __str__(self):
        return str(self.brand) + ': ' + str(self.title)

    class Meta:
        ordering = ['brand']
        unique_together = ['title', 'brand']


class Brand(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=100)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='children', blank=True, null=True)
    slug = models.SlugField(allow_unicode=True, null=True, editable=False)
    level = models.IntegerField(default=1)

    def save(self, *args, **kwargs):
        self.slug = slugify(transliterate(self.name))

        if not self.parent:
            self.level = 0

        super().save(*args, **kwargs)

    def __str__(self):
        full_path = [self.name]
        k = self.parent
        while k is not None:
            full_path.append(k.name)
            k = k.parent
        full_path.reverse()
        return ' -> '.join(full_path)

    class Meta:

        unique_together = ['parent', 'name']


class SaleApply(models.Model):
    item = models.OneToOneField('Item', on_delete=models.CASCADE, null=True)
    sale_rate = models.FloatField()

    def save(self, *args, **kwargs):
        self.item.apply_sale(self.sale_rate)
        super().save(*args, **kwargs)

    def delete(self):
        self.item.unapply_sale()
        super().delete()


class Review(models.Model):
    VALUES = (
        (1,'1'),
        (2,'2'),
        (3,'3'),
        (4,'4'),
        (5,'5')
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    rate = models.PositiveIntegerField(choices=VALUES, default=0)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.user) + ': ' + str(self.text)


class SalesRecord(models.Model):
    item = models.ForeignKey('Item', on_delete=models.CASCADE, related_name='sale_records')
    amount = models.PositiveIntegerField(default=0)
    total_price = models.FloatField(default=0)
    time = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        self.total_price = round(self.item.sale_price * self.amount, 2)
        super().save(*args, **kwargs)


class InOutRecord(models.Model):
    item = models.ForeignKey('Item', on_delete=models.CASCADE, related_name='in_records')
    amount = models.PositiveIntegerField(default=0)
    mode = models.CharField(max_length=200)
    time = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if self.mode == "arrived":
            self.item.add_items(self.amount)
        if self.mode == "removed":
            self.item.rem_items(self.amount)
        super().save(*args, **kwargs)



def transliterate(string):
    letters = {
        'а':'a', 'б':'b', 'в':'v', 'г':'g', 'д':'d', 'е':'e', 'є':'ye',
        'ж':'zh', 'з':'z', 'и':'y', 'і':'i', 'ї':'yi', 'й':'y', 'к':'k',
        'л':'l', 'м':'m', 'н':'n', 'о':'o', 'п':'p', 'р':'r', 'с':'s',
        'т':'t', 'у':'u', 'ф':'f', 'х':'kh', 'ц':'ts', 'ч':'ch', 'ш':'sh',
        'щ':'shch', 'ь':'', 'ю':'yu', 'я':'ya', '\'':'-'
    }

    string = string.lower()

    for char in string:
        if char in letters.keys():
            string = string.replace(char, letters[char])

    return string

shop_site/shop/views.py
from django.shortcuts import render, Http404
from django.views import View
from django.views.generic import (
    TemplateView, ListView, DetailView
)

from shop import models
from django.db.models import Sum, Q



class NavBarMixin(object):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = categorize(models.Category.objects.all())
        context['brands'] = models.Brand.objects.all()

        return context


class SideBarMixin(object):

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['breadcrumb'] = []

        # breadcrumb context
        categories = models.Category.objects.all()
        category = None
        parent = None
        for i in self.kwargs.values():
            category = categories.get(slug=i, parent=parent)
            context['breadcrumb'].append(category)
            parent = category

        # sizes
        context['masses'] = models.Article.objects.filter(
            Q(category=category) |
            Q(category__parent=category)
        ).exclude(items__mass__isnull=True).values_list('items__mass', flat=True)

        context['volumes'] = models.Article.objects.filter(
            Q(category=category) |
            Q(category__parent=category)
        ).exclude(items__volume__isnull=True).values_list('items__volume', flat=True)

        context['sizes'] = models.Article.objects.filter(
            Q(category=category) |
            Q(category__parent=category)
        ).exclude(items__size__isnull=True).values_list('items__size', flat=True)

        # brands
        context['brand'] = models.Brand.objects.filter(
            Q(articles__category=category) |
            Q(articles__category__parent=category)
        ).distinct()

        # ratings
        context['raitings'] = models.Review.objects.values_list('rate', flat=True)

        return context


class FilterMixin(object):

    def apply_filters(self, queryset):

        if self.request.GET:
            filters_dict = self.request.GET

            for key in filters_dict.keys():
                if key == "sale":
                    queryset = queryset.filter(items__sale=filters_dict[key]).distinct()
                if key == "brand":
                    queryset = queryset.filter(brand__name=filters_dict[key])
                if key == "rate":
                    queryset = queryset.filter(average_rate__gte=filters_dict[key])
                if key == "mass":
                    queryset = queryset.filter(items__mass=filters_dict[key]).distinct()
                if key == "volume":
                    queryset = queryset.filter(items__volume=filters_dict[key]).distinct()
                if key == "size":
                    queryset = queryset.filter(items__size=filters_dict[key]).distinct()

        return queryset


class HomePage(NavBarMixin,ListView):
    model = models.Article
    template_name = 'shop/index.html'
    context_object_name = 'articles'

    def get_queryset(self):
        queryset = models.Article.objects.filter(items__sale=True).distinct()
        return queryset

    def get_context_data(self):
        context = super().get_context_data()
        sales_dict = models.SalesRecord.objects.values('item').annotate(total_amount=Sum('amount')).order_by('-total_amount')[:40]
        sales_context_dict = {'articles': set()}
        for i in sales_dict.all():
            id = i['item']
            sales_context_dict['articles'].add(models.Article.objects.get(items__id=id))
        context['bestsellers'] = sales_context_dict

        return context


class ProductsPage(NavBarMixin,SideBarMixin,FilterMixin,ListView):
    model = models.Article
    template_name = 'shop/content.html'
    context_object_name = 'articles'
    paginate_by = 12
    paginate_orphans = 4

    def get_queryset(self):
        kwargs = self.kwargs
        categories = models.Category.objects.all()
        parent=None

        for slug in self.kwargs.values():
            category = categories.get(slug=slug, parent=parent)

            if not category:
                raise Http404
            else:
                parent = category

        if len(self.kwargs.values()) == 1:
            queryset = models.Article.objects.filter(category__parent__parent=category)
        elif len(self.kwargs.values()) == 2:
            queryset = models.Article.objects.filter(category__parent=category)
        elif len(self.kwargs.values()) == 3:
            queryset = models.Article.objects.filter(category=category)

        queryset = self.apply_filters(queryset)

        return queryset


class ArticleDetail(NavBarMixin, DetailView):
    model = models.Article
    context_object_name = 'article'
    template_name = 'shop/article_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['average_rate'] = self.object.get_average_rate()
        return context





def categorize(category_model):

    res_list = []
    queryset_0 = category_model.filter(parent=None)
    for i in queryset_0:
        dict_0 = {
            'name': i.name,
            'slug': i.slug,
            'subcategories': []
        }
        queryset_1 = category_model.filter(parent=i)
        for j in queryset_1:
            dict_1 = {
                'name': j.name,
                'slug': j.slug,
                'subcategories': []
            }
            queryset_2 = category_model.filter(parent=j)
            for k in queryset_2:
                dict_2 = {
                    'name': k.name,
                    'slug': k.slug
                }
                dict_1['subcategories'].append(dict_2)
            dict_0['subcategories'].append(dict_1)
        res_list.append(dict_0)
    return res_list

shop_site/shop/templates/shop/_article_thumbnail.html
<a href="{% url 'shop:about_article' slug=article.slug %}">
    <div class="card">
      <div class="container">
        <img src="{{ article.image.url }}" class="card-img-top" alt="...">
      </div>
      <div class="card-body">
        <h6>
          {% for item in article.items.all %}
            {% if forloop.counter == 1 %}
              <span class="badge badge-success">{{ item.mass }}</span>
            {% else %}
              <span class="badge badge-default">{{ item.mass }}</span>
            {% endif %}
          {% endfor %}
        </h6>
        <div class="container">
          <p class="card-text"><strong>{{ article.brand }}</strong> {{ article.title }}</p>
        </div>
  
        {% if article.get_average_rate < 1 %}
          <i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
        {% elif article.get_average_rate == 1 %}
          <i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
        {% elif article.get_average_rate > 1 and article.get_average_rate < 2 %}
          <i class="fas fa-star"></i><i class="fas fa-star-half-alt"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
        {% elif article.get_average_rate == 2 %}
          <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
        {% elif article.get_average_rate > 2 and article.get_average_rate < 3 %}
          <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star-half-alt"></i><i class="far fa-star"></i><i class="far fa-star"></i>
        {% elif article.get_average_rate == 3 %}
          <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
        {% elif article.get_average_rate > 3 and article.get_average_rate < 4 %}
          <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star-half-alt"></i><i class="far fa-star"></i>
        {% elif article.get_average_rate == 4 %}
          <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i>
        {% elif article.get_average_rate > 4 and article.get_average_rate < 5 %}
          <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star-half-alt"></i>
        {% else %}
          <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>
        {% endif %}

        <div class="row row-cols-2">

            <div class="col" style="color: red">
              <strong>{{ article.items.first.sale_price }} грн</strong>
            </div>
            {% if article.items.first.sale == True %}
              <div class="col" style="text-decoration: line-through">
                {{ article.items.first.price }} грн
              </div>
            {% endif %}
        </div>
        <h6><span class="badge badge-secondary">Більше варіантів</span></h6>

      </div>
    </div>
  </a>

shop_site/shop/templates/shop/article_detail.html
{% extends 'shop/base.html' %}
{% load static %}

{% block content %}

  <div class="container-fluid" style="padding: 0px;">

    <!-- bread crumb -->
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'shop:home' %}">ГОЛОВНА</a></li>
          <li class="breadcrumb-item"><a href="{% url 'shop:products' category=article.category.parent.parent.slug %}">{{ article.category.parent.parent.name|upper }}</a></li>
          <li class="breadcrumb-item"><a href="{% url 'shop:products' category=article.category.parent.parent.slug sub_cat_1=article.category.parent.slug %}">{{ article.category.parent.name|upper }}</a></li>
          <li class="breadcrumb-item"><a href="{% url 'shop:products' category=article.category.parent.parent.slug sub_cat_1=article.category.parent.slug sub_cat_2=article.category.slug %}">{{ article.category.name|upper }}</a></li>
        </ol>
      </nav>
    </div>
    <!-- bread crumb end -->

    <!-- main division -->
    <div class="main-content">
      <div class="container">
        <div class="row">
          <div class="col-12 col-sm-6 col-md-5">
            <div class="container">
              <img src="{{article.image.url}}" alt="">
            </div>
          </div>
          <div class="col-12 col-sm-6 col-md-7">
            <div class="row row-cols-1">
              <div class="col">
                <div class="container art-label">
                  <h2>{{ article.title }}</h2>
                  <h6 style="color: #0fa602">від {{ article.brand }}</h6>
                  <p>
                    {% if average_rate < 1 %}
                      <i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
                    {% elif average_rate == 1 %}
                      <i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
                    {% elif average_rate > 1 and average_rate < 2 %}
                      <i class="fas fa-star"></i><i class="fas fa-star-half-alt"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
                    {% elif average_rate == 2 %}
                      <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
                    {% elif average_rate > 2 and average_rate < 3 %}
                      <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star-half-alt"></i><i class="far fa-star"></i><i class="far fa-star"></i>
                    {% elif average_rate == 3 %}
                      <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
                    {% elif average_rate > 3 and average_rate < 4 %}
                      <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star-half-alt"></i><i class="far fa-star"></i>
                    {% elif average_rate == 4 %}
                      <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i>
                    {% elif average_rate > 4 and average_rate < 5 %}
                      <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star-half-alt"></i>
                    {% else %}
                      <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>
                    {% endif %}



                    <a href="#" style="margin-left: 10px; color: #0fa602"> Відгуки {{ article.reviews.count }}</a>
                  </p>
                </div>
              </div>
            </div>

            <div class="tab-content" id="pills-tabContent">
              <div class="tab-pane fade show active" id="first" role="tabpanel" aria-labelledby="first-tab">
                  <div class="row row-cols-2">
                      <div class="col">
                        <div class="container art-pricing" style="bottom: 0px; position: absolute">
                            <p style="color: #6b705c;"> ЦІНА:
                              <span style="padding-left: 15px; color: red; font-weight: bold">{{ article.items.first.sale_price }} грн</span>
                              {% if article.items.first.sale == True %}
                                <span style="padding-left: 15px; text-decoration: line-through">{{ article.items.first.price }} грн</span>
                              {% endif %}
                            </p>
                            <hr/>
                        </div>
                      </div>

                      <div class="col">
                        <div class="container art-cart">
                          <div class="card" style="height: 150px; max-width: 200px; margin-bottom: 15px;">
                            <div class="card-body">
                              <form class="" method="get">
                                <label style="color: #6b705c; font-size: 12px;" for="amount">КІЛЬКІСТЬ:</label>
                                <input style="height: 40px; margin-bottom: 10px;" class="w-100" type="number" id="amount" name="amount" value="1">

                                <input type="hidden" name="item_id" value="{{ article.items.first.id }}">

                                <input type="submit" class="btn btn-success w-100" name="" value="До кошика">
                              </form>
                              <!-- <p style="color: #6b705c;">КІЛЬКІСТЬ:</p>
                              <input type="number"/> -->
                            </div>
                          </div>
                        </div>
                      </div>
                  </div>
              </div>

              {% for item in article.items.all|slice:"1:" %}
                <div class="tab-pane fade" id="item_{{item.id}}" role="tabpanel" aria-labelledby="tab_{{item.id}}">
                  <div class="row row-cols-2">
                      <div class="col">
                        <div class="container art-pricing" style="bottom: 0px; position: absolute">
                            <p style="color: #6b705c;"> ЦІНА:
                              <span style="padding-left: 15px; color: red; font-weight: bold">{{ item.sale_price }} грн</span>
                              {% if item.sale == True %}
                                <span style="padding-left: 15px; text-decoration: line-through">{{ item.price }} грн</span>
                              {% endif %}
                            </p>
                            <hr/>
                        </div>
                      </div>

                      <div class="col">
                        <div class="container art-cart">
                          <div class="card" style="height: 150px; max-width: 200px; margin-bottom: 15px;">
                            <div class="card-body">
                              <form class="" method="get">
                                <label style="color: #6b705c; font-size: 12px;" for="amount">КІЛЬКІСТЬ:</label>
                                <input style="height: 40px; margin-bottom: 10px;" class="w-100" type="number" id="amount" name="amount" value="1">

                                <input type="hidden" name="item_id" value="{{ item.id }}">

                                <input type="submit" class="btn btn-success w-100" name="" value="До кошика">
                              </form>
                              <!-- <p style="color: #6b705c;">КІЛЬКІСТЬ:</p>
                              <input type="number"/> -->
                            </div>
                          </div>
                        </div>
                      </div>
                  </div>
                </div>
              {% endfor %}
            </div>

            <div class="row">
              <div class="col-6">
                <div class="container art-sizes">
                  <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
                    <li class="nav-item" role="presentation">
                      <a class="nav-link active" id="first-tab" data-toggle="pill" href="#first" role="tab" aria-controls="first" aria-selected="true">
                        {{ article.items.first.mass }}
                      </a>
                    </li>
                    {% for item in article.items.all|slice:"1:" %}
                      <li class="nav-item" role="presentation">
                        <a class="nav-link" id="tab_{{item.id}}" data-toggle="pill" href="#item_{{item.id}}" role="tab" aria-controls="item_{{item.id}}" aria-selected="false">
                          {{ item.mass }}
                        </a>
                      </li>
                    {% endfor %}
                  </ul>
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>

    <div class="article-description">
      <div class="container">
        <div class="row">
          <div class="col-12 col-md-8">
            <ul class="nav nav-tabs" id="myTab" role="tablist">
              <li class="nav-item" role="presentation">
                <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Опис товару</a>
              </li>
              <li class="nav-item" role="presentation">
                <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Інгредієнти</a>
              </li>
              <li class="nav-item" role="presentation">
                <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Годування</a>
              </li>
            </ul>
            <div class="tab-content" id="myTabContent">
              <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                <h2 style="margin: 20px 0px 20px;">Опис товару</h2>
                {{article.description}}
              </div>
              <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                <h2 style="margin: 20px 0px 20px;">Інгредієнти</h2>
                {{article.contents}}
              </div>
              <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
                <h2 style="margin: 20px 0px 20px;">Годування</h2>
                {{article.manual}}
              </div>
            </div>
          </div>

          <div class="col-12 col-md-4">

          </div>
        </div>

      </div>
    </div>

    <div class="article-reviews">
      <div class="container">
        <div class="row">
          <div class="col-12 col-md-6">
            <h2 style="margin: 20px 0px 20px;">Відгуки</h2>
          </div>
          <div class="col-12 col-md-6">
            <form action="" method="get" style=" display: flex; justify-content: right;">
              <input style="margin: 20px 0px 20px;" type="submit" class="btn btn-success" value="Залишити відгук">
            </form>
          </div>
        </div>

        {% for rev in article.reviews.all %}
          <div class="rev-body">
            {% if rev.rate == 0 %}
              <i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
            {% elif rev.rate == 1 %}
              <i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
            {% elif rev.rate == 2 %}
              <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
            {% elif rev.rate == 3 %}
              <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
            {% elif rev.rate == 4 %}
              <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i>
            {% else %}
              <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>
            {% endif %}
            <span style="margin-left: 20px; color: #6b705c">
              {{ rev.user }},  {{ rev.date_updated }}
            </span>
            <div class="rev-text">
              {{ rev.text }}
            </div>
          </div>
          <hr/>
        {% endfor %}





      </div>

    </div>





  </div>

{% endblock %}